gateway:
  loglevel: DEBUG
  prefix: /services/dask-gateway
  backend:
    scheduler:
      cores:
        request: 0.1
      memory:
        request: 256M

    worker:
      cores:
        request: 0.1
      memory:
        request: 256M

controller:
  loglevel: DEBUG
  completedClusterMaxAge: 60
  completedClusterCleanupPeriod: 30

traefik:
  loglevel: INFO
  service:
    ports:
      web:
        port: 30200
