# Chart.yaml v2 reference: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: dask-gateway
version: 0.0.1-set.by.chartpress
appVersion: "2022.4.0"
description: A multi-tenant server for deploying and managing Dask clusters
home: https://gateway.dask.org/
sources:
  - https://github.com/dask/dask-gateway/
icon: https://docs.dask.org/en/latest/_images/dask_icon_no_pad.svg
kubeVersion: ">=1.20.0-0"
