apiVersion: v1
name: dask-gateway
version: 0.7.1
appVersion: 0.7.1
description: A multi-tenant server for deploying and managing Dask clusters
home: https://gateway.dask.org/
sources:
  - https://github.com/dask/dask-gateway/
