# Chart.yaml v2 reference: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: dask-gateway
version: 0.0.1-set.by.chartpress
appVersion: "2022.10.0"
description: A multi-tenant server for deploying and managing Dask clusters
home: https://gateway.dask.org/
sources:
  - https://github.com/dask/dask-gateway/
icon: https://avatars3.githubusercontent.com/u/17131925?v=3&s=200
kubeVersion: ">=1.20.0-0"
